import { Head, Html, Main, NextScript } from "next/document";

export default function Document() {
    return (
        <Html className="min-h-screen">
            <Head>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <body className="min-h-screen bg-white transition-colors dark:bg-slate-950">
                <Main />
                <NextScript />
            </body>
        </Html>
    );
}
